language: csharp
sudo: false
mono:
  - 4.8.1
  - latest
os:
  - linux
  - osx
matrix:
  exclude:
    - os: osx
      mono: latest
  allow_failures:
    - os: osx
    - mono: latest
  fast_finish: true
script:
  - ./build.sh --target "Travis"